# Generated by Django 2.0.2 on 2018-03-16 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chalkboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteChalkboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Chalkboard')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermissionChalkboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionChalkboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('permission', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text_content', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageStickyNote',
            fields=[
                ('stickynote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.StickyNote')),
                ('image_content', models.URLField()),
            ],
            bases=('notes.stickynote',),
        ),
        migrations.CreateModel(
            name='VideoStickyNote',
            fields=[
                ('stickynote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.StickyNote')),
                ('video_content', embed_video.fields.EmbedVideoField()),
            ],
            bases=('notes.stickynote',),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='chalkboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Chalkboard'),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouppermissionchalkboard',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.PermissionChalkboard'),
        ),
        migrations.AddField(
            model_name='grouppermissionchalkboard',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chalkboard',
            name='group_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.GroupPermissionChalkboard'),
        ),
        migrations.AddField(
            model_name='chalkboard',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
