# Generated by Django 2.0.2 on 2018-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynotetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
