# Generated by Django 2.0.2 on 2018-02-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
