# Generated by Django 2.0.2 on 2018-03-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180305_1438'),
        ('notes', '0002_auto_20180305_1543'),
    ]

    operations = [
    ]
